comment out another failing codeql/sarif action

diff --git a/.github/workflows/checkStyle.yml b/.github/workflows/checkStyle.yml
--- a/.github/workflows/checkStyle.yml
+++ b/.github/workflows/checkStyle.yml
@@ -31,18 +31,18 @@ jobs:
       - name: Ktlint
         run: ./gradlew ktlintCheck
 
-      - name: Upload ktlint SARIF files
-        if: success() || failure()
-        uses: github/codeql-action/upload-sarif@v4
-        with:
-          sarif_file: 'app/build/reports/ktlint'
-          category: ktlint
+      # TODO: Fix me... https://github.blog/changelog/2025-07-21-code-scanning-will-stop-combining-multiple-sarif-runs-uploaded-in-the-same-sarif-file/
+#      - name: Upload ktlint SARIF files
+#        if: success() || failure()
+#        uses: github/codeql-action/upload-sarif@v4
+#        with:
+#          sarif_file: 'app/build/reports/ktlint'
+#          category: ktlint
 
       - name: Detekt
         if: success() || failure()
         run: ./gradlew detekt
 
-# TODO: Fix me... https://github.blog/changelog/2025-07-21-code-scanning-will-stop-combining-multiple-sarif-runs-uploaded-in-the-same-sarif-file/
 #      - name: Upload detekt SARIF files
 #        if: success() || failure()
 #        uses: github/codeql-action/upload-sarif@v3
